name: MC Terraform CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

jobs:
  deploy-dev:
    name: MC Deploy to Dev
    runs-on: ubuntu-latest
    environment: mc-dev
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: MC Terraform Init & Apply - Dev
        working-directory: pipeline/dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          terraform init
          terraform apply -auto-approve

  deploy-uat:
    name: MC Deploy to UAT
    runs-on: ubuntu-latest
    environment: mc-uat-approval
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: MC Terraform Init & Apply - UAT
        working-directory: pipeline/uat
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          terraform init
          terraform apply -auto-approve

  deploy-prod:
    name: MC Deploy to Prod
    runs-on: ubuntu-latest
    environment: mc-prod-approval
    needs: deploy-uat
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: MC Terraform Init & Apply - Prod
        working-directory: pipeline/prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          terraform init
          terraform apply -auto-approve
